### PR TITLE
Ruby 3.2 compatibility

### PR DESCRIPTION
**Pull request by sudharsan-p**
- Rubygems started cleaning build artificats since v3.4 [#6133](https://github.com/rubygems/rubygems/pull/6133). Requiring from `lib` instead of `ext`

- Generated `cbc_wrap.c` using `SWIG 4.1.1` to fix [Ruby 3.2 warning](https://bugs.ruby-lang.org/issues/18007) related to [swig_runtime_data](https://github.com/swig/swig/issues/2257). There will still be similar warnings which are [fixed in swig master](https://github.com/swig/swig/pull/2527), but a newer version of SWIG with this fix is yet to be released.

### CODE REVIEW

**Comment by sundarraja** [comment]
@gverger @soutaro @halfdan Can you help with merging these changes?

**Comment by gverger** [comment]
Thank you for the PR @sudharsan-p 

I am on vacation at the moment and I'll be back to my computer in August.
I don't quite understand what is happening here, is rubygems installing in both ext and lib, but the last version now cleans ext ?
Was it installed in these 2 folders previously ?

If that's the case i would only need to merge this and upload the new version on rubygems, and that's it ?

**Comment by sudharsan-p** [comment]
@gverger
Thanks for the response
- `is rubygems installing in both ext and lib?` Yes. [Please refer](https://guides.rubygems.org/gems-with-extensions/)
- `but the last version now cleans ext` Yes. [Please refer](https://github.com/rubygems/rubygems/pull/6133)
- `Was it installed in these 2 folders previously` Yes. [Please refer](https://github.com/rubygems/rubygems/blob/master/lib/rubygems/ext/ext_conf_builder.rb#L47-L57)
- `If that's the case i would only need to merge this and upload the new version on rubygems, and that's it ?` Yes. I have also added one more [commit](https://github.com/gverger/cbc-wrapper/pull/6/commits/abfdb30e6a63fcc25b1c6eb3ec72edace177aef7) to this PR. We have tested these changes and they work fine for us

**Comment by sundarraja** [comment]
@gverger Can you check this PR?

**Comment by gverger** [comment]
Merged, and I pushed version 2.9.9.5 to rubygems.

Thanks a lot for your contribution!

**Pull request merged**
